### ISSUE TITLE
Errors on macbook

### ISSUE THREAD

**Issue by tonyschuite** [brutesque/touchdesigner-orbbec-astra#1]
Hi there, i have been playing around with this but i get the following error

Traceback (most recent call last):
  File "/project1/astra1_callbacks", line 500, in onCook
  File "/project1/astra1_callbacks", line 405, in update_parameters
  File "/project1/astra1_callbacks", line 248, in populate_menus
IndexError: list index out of range

It seems something is incorrect. i have no idea where to look.

this happens on intel macbook pro.  latest TD install

**Comment by brutesque** [comment]
Did you check the readme?
